### PR TITLE
bugfix for missing brrrrt

### PR DESCRIPTION
**Pull request by nomisum**
removing sound curve (didnt seem to work)
increasing range and volume a bit

### CODE REVIEW

**Comment by Zabuzard** [comment]
Thanks for the request. Is this a pure _cosmetic_ change or does this fix issue #1 ?

The change seems to be minimal and only adjusts the range a bit. Why does it fix the issue (supposed it does)?

**Comment by nomisum** [comment]
I'm not sure *why* it works, the actual fix is removing the brackets (last param).

Currently trying to get my head around sound shaders, trying to improve the sounds as well (no gap when full auto).

Edit: Still trying to figure out whats going on. Dont merge until further notice 😄

**Comment by nomisum** [comment]
sooo i did some research:

sadly, its currently not possible to add soundshaders to plane cannons (yet). i hope this will be possible in the future, i added my sounds for tails and distance sound (muffled) to this PR already.

the used seamless sound is an edit of the original sound which doesnt have a nice tail (yet, as no sound shader). but it loops perfectly, so you can fire 2000 rounds without sound gaps.

if you prefer i could reduce this PR again to only fixing the issue (which is removing the loop param from soundBegin).

**Review by DerZade — APPROVED** [review]

**Comment by DerZade** [comment]
I have to correct myself. Nomisums fix seems to be flawed as well. 
We played yesterday a couple of hours on takistan with a few gun runs. 
Most of the time with no BRRRT.

**Comment by nomisum** [comment]
thats a pity. i will consider this a game bug then and come back to this when soundshaders become a thing.

**Pull request closed without merging**
